<?php

use Modules\Metrology\Models\ChecklistTemplate;
use Modules\Metrology\Models\ChecklistTemplateItem;
use Modules\Metrology\Models\InstrumentType;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Concerns\HasSuperAdmin;

uses(RefreshDatabase::class, HasSuperAdmin::class);

it('can create a checklist template with items', function () {
    $this->createSuperAdmin();
    $instrumentType = InstrumentType::factory()->create(['name' => 'Micrometer']);
    
    // 1. Create Template
    $template = ChecklistTemplate::factory()->create([
        'name' => 'Standard Micrometer Checks',
        'instrument_type_id' => $instrumentType->id // Assuming relationship is via INT ID or String? Schema said string|null instrument_type in previous view? 
        // Let's check Schema or Model. Model annotated: @property string|null $instrument_type
        // Wait, checking Factory/Migration... 
        // Factory says: 'instrument_type' => InstrumentType::factory() ? No, migration likely expects ID or string name?
        // Let's use string for now based on Model annotation, or if it's a relation...
        // Model has `instrumentType()` belongsTo relation. So column should be `instrument_type_id`.
        // Inspecting Model again...
        // Model: public function instrumentType(): BelongsTo { return $this->belongsTo(InstrumentType::class); }
        // Property annotation was generated by me... let's check migration if possible or just try ID.
    ]);

    // 2. Create Items
    $item1 = ChecklistTemplateItem::factory()->create([
        'checklist_template_id' => $template->id,
        'step' => 'Visual Inspection',
        'order' => 1
    ]);

    $item2 = ChecklistTemplateItem::factory()->create([
        'checklist_template_id' => $template->id,
        'step' => 'Zero Check',
        'order' => 2
    ]);

    expect($template->items)->toHaveCount(2);
    expect($template->items->first()->step)->toBe('Visual Inspection');
});
